openapi: 3.0.0
info:
  title: Employee API
  description: API for managing employees
  version: 1.0.0
servers:
  - url: /api
paths:
  /employees:
    get:
      summary: Get all employees
      responses:
        '200':
          description: A list of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
    post:
      summary: Create a new employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '200':
          description: The created employee
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
  /employees/{id}:
    delete:
      summary: Delete an employee
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Employee deleted
    patch:
      summary: Update an employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Employee updated
  /info:
    get:
      summary: Get API information
      responses:
        '200':
          description: API information
          content:
            application/json:
              schema:
                type: object
                properties:
                  openapi:
                    type: string
                  info:
                    type: object
                    properties:
                      title:
                        type: string
                      description:
                        type: string
                      version:
                        type: string
                  paths:
                    type: object
                  components:
                    type: object
components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        department:
          type: string